dev_mode: true
mode:
  - all

db:
  host: localhost
  port: 15432
  database: opentdf
  user: postgres
  password: changeme
  sslmode: disable
  schema: opentdf
  runMigrations: true

server:
  port: 8080
  auth:
    enabled: true
    enforceDPoP: false
    audience: "http://localhost:8080"
    issuer: "http://localhost:15433"
    policy:
      client_id_claim: "client_id"
      username_claim: "preferred_username"
      groups_claim: "realm_access.roles"
  tls:
    enabled: false
  cors:
    enabled: true
    allowedorigins:
      - "*"
  grpc:
    reflectionEnabled: true
  cryptoProvider:
    type: standard
    standard:
      keys:
        - kid: r1
          alg: rsa:2048
          private: data/kas-private.pem
          cert: data/kas-cert.pem
        - kid: e1
          alg: ec:secp256r1
          private: data/kas-ec-private.pem
          cert: data/kas-ec-cert.pem

services:
  entityresolution:
    mode: claims
  policy:
    list_request_limit_max: 2500
    list_request_limit_default: 1000
